Platzigram/urls.py
"""Platigram URLs module."""
#Django
from django import urls
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


from users import views as users_views
from users import views as logout_view

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URL."""

# Django
from django.urls import path 

# Views
from posts import views 

urlpatterns = [
    path(
        route='',
        view=views.list_posts,
        name='feed'
    ),


    path(
        route='posts/new/', 
        view=views.create_posts, 
        name='create'),
]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path 
from django.views.generic import TemplateView

# View
from users import views

urlpatterns = [


    # Posts
    path(
        route='<str:username>/',
        view=TemplateView.as_view(template_name='users/detail.html'),
        name='login'
    ),

    # Management
    path(
        route='users/login/', 
        view=views.login_view, 
        name='login'
    ),
    path(
        route='users/logout/', 
        view=views.logout_view, 
        name='logout'
    ),
    path(
        route='users/signup/', 
        view=views.signup_view, 
        name='signup'
    ),
    path(
        route='users/me/profile/', 
        view=views.update_profile, 
        name='update_profile'
    ),
]

posts/models.py
"""Post models."""

# Django
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=250)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""Users forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    """sign up form."""

    username = forms.CharField(label=False,min_length=4,max_length=50, widget = forms.TextInput(attrs={'placeholder':'Nombre de usuario','class': 'form-control','required': True}))

    password = forms.CharField(
        label=False,
        max_length=70, 
        widget=forms.PasswordInput(attrs={'placeholder':'Password','class': 'form-control','required': True}))

    password_confirmation = forms.CharField(
        label=False,
        max_length=70, widget=forms.PasswordInput(attrs={'placeholder':'Confirm your password','class': 'form-control','required': True}))

    first_name = forms.CharField(
        label=False,
        min_length=2,
        max_length=50,widget = forms.TextInput(attrs={'placeholder':'Name','class': 'form-control','required': True}))

    last_name = forms.CharField(
        label=False,
        min_length=2,
        max_length=50,widget = forms.TextInput(attrs={'placeholder':'Last Name','class': 'form-control','required': True}))

    email = forms.EmailField(
        label=False,
        min_length=6,
        max_length=70,widget=forms.EmailInput(attrs={'placeholder':'email','class': 'form-control','required': True}))

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()




class ProfileForm(forms.Form):
    """Profile form."""
    
    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

posts/views.py
"""Posts views."""

# Django
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Forms
from posts.form import PostForm

# Models
from posts.models import Post


@login_required
def list_posts(request):
    """List existing posts."""
    posts = Post.objects.all().order_by('-created')
    return render(request, 'posts/feed.html', {'posts': posts})

@login_required
def create_posts(request):
    """Create new post view."""
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('feed')


    else:
        form = PostForm()

    return render(
        request=request,
        template_name='posts/new.html',
        context={
            'form': form,
            'user': request.user,
            'profile': request.user.profile
        }
    )

users/views.py
"""Users views."""

# Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

# Forms
from users.forms import ProfileForm, SignupForm

@login_required
def update_profile(request):
    """Update a user's profile view."""
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()


            messages.success(request, 'Profile updated correctly')
            return redirect('update_profile')
    else:
        form = ProfileForm()
    
    return render(
        request=request,
        template_name='users/update_profile.html',
        context={
            'profile': profile,
            'users': request.user,
            'form': form
        }
    )

def login_view(request):
    """Login view."""
    if request.method == 'POST':
        print('*' * 10)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            # Redirect to a success page.
            return redirect('feed')
        else:
            # Return an 'invalid login' error message.
            return render(request, 'users/login.html', {'error': 'Invalid username and password'})
    return render(request, 'users/login.html')

def signup_view(request):
    """Sign up view."""
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignupForm()

    return render(
        request= request,
        template_name='users/signup.html',
        context={'form': form},
    )
    
@login_required
def logout_view(request):
    """Logout a user."""
    logout(request)
    return redirect('login')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Platzigram {% block head_content %}{% endblock %}</title>


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>
<body>

    {% include "nav.html" %}

    <div class="container nt-5 pt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %} 
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/posts/feed.html
{% extends "base.html" %}



{% block container %}
    <div class="container">
        <div class="row">
            {% for post in posts %}
            <div class="col-sm-0 col-md-8 mt-5 offset-md-2 mt-5 p-0 post-container">
                <div class="media pt-3 pl-3 pb-1">
                    <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    <div class="media-body">
                        <p style="margin-top:5px;">{{ post.user.get_full_name }}</p>
                    </div>
                </div>

                <img style="width: 100%" src="{{ post.photo.url }}" alt="{{ post.title }}">

                <h6 class="ml-1 mt-1">{{ post.title }}</h6>

                <p class="mt-1 ml-2">
                    <a href="" style="color:grey; font-size: 20px;">
                        <i class="far fa-heart"></i>
                    </a> 30 likes
                </p>
                <p class="ml-2 mt-0 mb-2">
                    <b>{{post.title}}</b> - <small>{{post.created}}</small>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}```

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ request.user.profile.picture.url }}" alt="@{{ request.user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ request.user.username }}
                    {% if request.user == user %}
                        <a
                            href="{% url 'users:update_profile' %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ request.user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ request.user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ request.user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ request.user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram Sign In</title>
{% endblock %}

{% block container %} 

    {% if error %}
        <p class="alert alert-danger"> {{ error }}</p>
    {% endif %}


    <form method="POST" action="{% url 'login' %}"> 
        {% csrf_token %}

        <div class="form-group">
            <input type="text" class="form-control form-control-lg" name="username" placeholder="Username">
        </div>

        <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Password">
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit"> Sign in! </button>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url 'signup' %}">Sign up here!</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %} 

{% block head_content %} 
<title>Platzigram sign up</title>
{% endblock %}

{% block container %} 
    
    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit"> Register </button>



    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4"id="profile-box">
            <form action="{% url 'update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

              
                <div class='media'>
                    {%if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50"/>
                    {% else %}
                      <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50"/>
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4"> @{{ user.username }} | {{ user.get_full_name }} </h5>
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{error}}
                 </div> 
                {% endfor %}
                 

                <hr><br>
                <!--Website Field-->
                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %} is-invalid {% endif %}"
                            type="text"
                            name="website"
                            placeholder="Website"
                            
                            value="{% if form.errors %} {{form.website.value}} {% else %} {{ profile.website }} {% endif %}"
                            />
                          <div class="invalid-feedback">
                            {% for error in form.website.errors %} 
                            {{error}}
                            {% endfor %}
                          </div>
                </div>
            
                <div class="form-group">
                    <label>Biography</label>
                    <!--si ocurre un error lo muestra-->
                    <textarea 
                    class="form-control {% if form.biography.errors %} is-invalid {% endif %}" 
                    name="biography"
                    >{% if form.errors %}{{form.biography.value}}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <!--acá muestra el error dentro de div en un cuadro rojo, con la descipcion-->

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %} 
                        {{error}}
                        {% endfor %}
                      </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
                        type="text"
                        name="phone_number"
                        {% if form.errors %} {{form.phone_number.value}} {% else %} {{ profile.phone_number }} {% endif %}
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %} 
                        {{error}}
                        {% endfor %}
                      </div>
              </div>

                <button type="submit"class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}